"""
scripts/copy_runtime_significance.py
====================================
Prepare runtime-significance outputs from already measured inference metrics.

This script does not retrain models. It reads the saved metrics generated by
the existing evaluation scripts and copies the measured inference/runtime
values into results/runtime_significance for downstream analysis.

Usage
-----
    python scripts/copy_runtime_significance.py
"""

from __future__ import annotations

import csv
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DST = ROOT / "results" / "runtime_significance"
MODEL_ORDER = ["unet", "unet_lomix", "fno"]
MODEL_LABELS = {
    "unet": "U-Net",
    "unet_lomix": "U-Net (LoMix)",
    "fno": "FNO",
}


def _is_finite(value) -> bool:
    return isinstance(value, (int, float)) and math.isfinite(value)


def load_metric(model_key: str) -> dict | None:
    path = ROOT / "results" / f"{model_key}_metrics.json"
    if not path.exists():
        print(f"[skip] Missing metrics file: {path.name}")
        return None

    with path.open() as f:
        data = json.load(f)

    return data if isinstance(data, dict) else None


def main():
    DST.mkdir(parents=True, exist_ok=True)

    rows = []
    summary: dict[str, dict] = {}

    for model_key in MODEL_ORDER:
        metrics = load_metric(model_key)
        if not metrics:
            continue

        row = {
            "repeat": 0,
            "seed": 0,
            "model": model_key,
            "rmse": float(metrics.get("rmse", float("nan"))),
            "rel_l2": float(metrics.get("rel_l2", float("nan"))),
            "max_error": float(metrics.get("max_error", float("nan"))),
            "inference_time_s": float(metrics.get("inference_time_s", float("nan"))),
            "n_params": float(metrics.get("n_params", 0)),
        }
        rows.append(row)
        summary[model_key] = {
            "display_name": MODEL_LABELS[model_key],
            "rmse": row["rmse"],
            "rel_l2": row["rel_l2"],
            "max_error": row["max_error"],
            "inference_time_s": row["inference_time_s"],
            "n_params": row["n_params"],
            "source": "measured",
        }

    summary_path = DST / "runtime_significance_summary.json"
    with summary_path.open("w") as f:
        json.dump(
            {
                "status": "copied_from_measured_metrics",
                "models": summary,
            },
            f,
            indent=2,
        )

    csv_path = DST / "repeated_runs.csv"
    with csv_path.open("w", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["repeat", "seed", "model", "rmse", "rel_l2", "max_error", "inference_time_s", "n_params"],
        )
        writer.writeheader()
        for row in rows:
            writer.writerow(row)

    print(f"[runtime_significance] Copied measured metrics for {len(rows)} model(s)")
    print(f"[runtime_significance] Summary -> {summary_path}")
    print(f"[runtime_significance] CSV -> {csv_path}")
    if not rows:
        print("[warn] No measured metrics were found to copy")


if __name__ == "__main__":
    main()
